/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tiendapoo;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author HP
 */
public class JFCarbos extends javax.swing.JFrame {
//se crea a misma lista que la de menu
    private List<Alimentos> listaAlim;
    
//se crea sus getters y setters

    public List<Alimentos> getListaAlim() {
        return listaAlim;
    }

    public void setListaAlim(List<Alimentos> listaAlim) {
        this.listaAlim = listaAlim;
    }

    
    /**
     * Creates new form JFCarbos
     */
    public JFCarbos() {
        //componentes o caracteristicas de la ventana
       initComponents();
       this.setLocationRelativeTo(null);
       setSize(420, 340); 
       setDefaultCloseOperation(EXIT_ON_CLOSE);
       setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CBC = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtnombreC = new javax.swing.JTextField();
        txtcolorC = new javax.swing.JTextField();
        txtcaloriasC = new javax.swing.JTextField();
        txtpesoC = new javax.swing.JTextField();
        btnChos = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(102, 255, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nombre:");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(78, 44, 51, 15);

        jLabel2.setBackground(new java.awt.Color(102, 255, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Color:");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(78, 84, 36, 15);

        jLabel3.setBackground(new java.awt.Color(102, 255, 102));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Peso:");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(78, 164, 33, 15);

        jLabel4.setBackground(new java.awt.Color(102, 255, 102));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Calorias:");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(78, 124, 51, 15);

        CBC.setBackground(new java.awt.Color(102, 255, 102));
        CBC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CBC.setText("Si");
        CBC.setOpaque(true);
        CBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCActionPerformed(evt);
            }
        });
        getContentPane().add(CBC);
        CBC.setBounds(179, 208, 50, 19);

        jLabel5.setBackground(new java.awt.Color(102, 255, 102));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Es  Refinado?");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(78, 210, 83, 15);

        txtnombreC.setBackground(new java.awt.Color(153, 255, 153));
        getContentPane().add(txtnombreC);
        txtnombreC.setBounds(179, 40, 84, 22);

        txtcolorC.setBackground(new java.awt.Color(153, 255, 153));
        getContentPane().add(txtcolorC);
        txtcolorC.setBounds(179, 80, 84, 22);

        txtcaloriasC.setBackground(new java.awt.Color(153, 255, 153));
        getContentPane().add(txtcaloriasC);
        txtcaloriasC.setBounds(179, 120, 84, 22);

        txtpesoC.setBackground(new java.awt.Color(153, 255, 153));
        getContentPane().add(txtpesoC);
        txtpesoC.setBounds(179, 160, 84, 22);

        btnChos.setBackground(new java.awt.Color(51, 255, 51));
        btnChos.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnChos.setText("Crear");
        btnChos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChosMouseClicked(evt);
            }
        });
        getContentPane().add(btnChos);
        btnChos.setBounds(300, 250, 90, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiendapoo/NBN.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBCActionPerformed

    private void btnChosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChosMouseClicked
       //creamos variales y segun lo que se ingrese en la ventana se guardaran ahi
        String nombreC = txtnombreC.getText();
       String colorC = txtcolorC.getText();
       int caloriasC = Integer.parseInt(txtcaloriasC.getText());
       if (caloriasC <= 101 || caloriasC >300){
            JOptionPane.showMessageDialog(this, "Error, este alimento no es un carbohidrato, verifique");
            return;
        }
       int pesoC = Integer.parseInt(txtpesoC.getText());
       boolean esRefinado = CBC.isSelected();
       
       //se crea el objeto con la clase Carbohidratos, y sus parametros, lo que va a contener
       Carbohidratos carbos1 = new Carbohidratos(nombreC, colorC, caloriasC, pesoC, esRefinado);
       JOptionPane.showMessageDialog(this, carbos1);
       //se agrega la informacion a la lista creada
       listaAlim.add(carbos1);
       //se cierra la ventana y queda en el menu nuevamente
       this.setVisible(false);
       
    }//GEN-LAST:event_btnChosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCarbos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCarbos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCarbos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCarbos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCarbos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBC;
    private javax.swing.JButton btnChos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtcaloriasC;
    private javax.swing.JTextField txtcolorC;
    private javax.swing.JTextField txtnombreC;
    private javax.swing.JTextField txtpesoC;
    // End of variables declaration//GEN-END:variables
}
