/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tiendapoo;


import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class JFFrutasVerduras extends javax.swing.JFrame {
 
    private List<Alimentos> listaAlim; 

    public List<Alimentos> getListaAlim() {
        return listaAlim;
    }

    public void setListaAlim(List<Alimentos> listaAlim) {
        this.listaAlim = listaAlim;
    }

   
    
    
    /**
     * Creates new form JFFrutasVerduras
     */
    public JFFrutasVerduras() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(420, 340); // Tamaño fijo
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnombreF = new javax.swing.JTextField();
        txtcolorF = new javax.swing.JTextField();
        txtCaloriasF = new javax.swing.JTextField();
        txtpesoF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CBFruta = new javax.swing.JCheckBox();
        btnCrearF = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nombre:");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(67, 21, 51, 15);

        jLabel2.setBackground(new java.awt.Color(255, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Color:");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(67, 61, 36, 15);

        jLabel3.setBackground(new java.awt.Color(255, 102, 102));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Calorias:");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(67, 101, 51, 15);

        jLabel4.setBackground(new java.awt.Color(255, 102, 102));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Peso en Gramos:");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(67, 141, 101, 15);

        txtnombreF.setBackground(new java.awt.Color(153, 255, 153));
        txtnombreF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreFActionPerformed(evt);
            }
        });
        getContentPane().add(txtnombreF);
        txtnombreF.setBounds(180, 17, 85, 22);

        txtcolorF.setBackground(new java.awt.Color(153, 255, 153));
        getContentPane().add(txtcolorF);
        txtcolorF.setBounds(180, 57, 85, 22);

        txtCaloriasF.setBackground(new java.awt.Color(153, 255, 153));
        getContentPane().add(txtCaloriasF);
        txtCaloriasF.setBounds(180, 97, 85, 22);

        txtpesoF.setBackground(new java.awt.Color(153, 255, 153));
        getContentPane().add(txtpesoF);
        txtpesoF.setBounds(180, 137, 85, 22);

        jLabel5.setBackground(new java.awt.Color(255, 102, 102));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Es una Fruta?");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(67, 180, 83, 15);

        CBFruta.setBackground(new java.awt.Color(255, 102, 102));
        CBFruta.setText("Si");
        CBFruta.setOpaque(true);
        getContentPane().add(CBFruta);
        CBFruta.setBounds(180, 177, 40, 20);

        btnCrearF.setBackground(new java.awt.Color(51, 255, 51));
        btnCrearF.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnCrearF.setText("Crear");
        btnCrearF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearFMouseClicked(evt);
            }
        });
        btnCrearF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearFActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearF);
        btnCrearF.setBounds(300, 250, 90, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiendapoo/beneficios-saludables-frutas-verduras.jpeg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreFActionPerformed

    private void btnCrearFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearFMouseClicked
        String nombreFruta = txtnombreF.getText();
        String colorFruta = txtcolorF.getText();
        int caloriasFruta = Integer.parseInt(txtCaloriasF.getText());
        if (caloriasFruta >100 ){
            JOptionPane.showMessageDialog(this, "Error, este alimento no es una fruta, verifique");
            return;
        }
        int pesoFruta = Integer.parseInt(txtpesoF.getText());
        boolean esFruta = CBFruta.isSelected();
        
        FrutasVerduras fruta1 = new FrutasVerduras (nombreFruta, colorFruta, caloriasFruta, pesoFruta, esFruta);
        JOptionPane.showMessageDialog(this, fruta1);
        listaAlim.add(fruta1);
        this.setVisible(false);
       
        
    }//GEN-LAST:event_btnCrearFMouseClicked

    private void btnCrearFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFFrutasVerduras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFFrutasVerduras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFFrutasVerduras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFFrutasVerduras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFFrutasVerduras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBFruta;
    private javax.swing.JButton btnCrearF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCaloriasF;
    private javax.swing.JTextField txtcolorF;
    private javax.swing.JTextField txtnombreF;
    private javax.swing.JTextField txtpesoF;
    // End of variables declaration//GEN-END:variables

    void setListaAlimentos(List<Alimentos> listaAlimentos) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
