/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tiendapoo;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class JFGrasas extends javax.swing.JFrame {
private List<Alimentos> listaAlim; 

    public List<Alimentos> getListaAlim() {
        return listaAlim;
    }

    public void setListaAlim(List<Alimentos> listaAlim) {
        this.listaAlim = listaAlim;
    }

   
    /**
     * Creates new form JFGrasas
     */
    public JFGrasas() {
        initComponents();
       this.setLocationRelativeTo(null);
       setSize(420, 340); 
       setDefaultCloseOperation(EXIT_ON_CLOSE);
       setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtpesoG = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CBGrasa = new javax.swing.JCheckBox();
        btnCrearG = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnombreG = new javax.swing.JTextField();
        txtcolorG = new javax.swing.JTextField();
        txtCaloriasG = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtpesoG.setBackground(new java.awt.Color(255, 255, 102));
        getContentPane().add(txtpesoG);
        txtpesoG.setBounds(180, 137, 85, 22);

        jLabel5.setBackground(new java.awt.Color(51, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Es Saturado?");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(67, 180, 90, 15);

        CBGrasa.setBackground(new java.awt.Color(255, 153, 51));
        CBGrasa.setText("Si");
        CBGrasa.setOpaque(true);
        getContentPane().add(CBGrasa);
        CBGrasa.setBounds(180, 177, 50, 20);

        btnCrearG.setBackground(new java.awt.Color(51, 255, 51));
        btnCrearG.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnCrearG.setText("Crear");
        btnCrearG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearGMouseClicked(evt);
            }
        });
        btnCrearG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearGActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearG);
        btnCrearG.setBounds(300, 250, 90, 40);

        jLabel1.setBackground(new java.awt.Color(102, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nombre:");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(67, 21, 51, 15);

        jLabel2.setBackground(new java.awt.Color(51, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Color:");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(67, 61, 36, 15);

        jLabel3.setBackground(new java.awt.Color(51, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Calorias:");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(67, 101, 51, 15);

        jLabel4.setBackground(new java.awt.Color(51, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Peso en Gramos:");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(67, 141, 101, 15);

        txtnombreG.setBackground(new java.awt.Color(255, 255, 102));
        txtnombreG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreGActionPerformed(evt);
            }
        });
        getContentPane().add(txtnombreG);
        txtnombreG.setBounds(180, 17, 85, 22);

        txtcolorG.setBackground(new java.awt.Color(255, 255, 102));
        getContentPane().add(txtcolorG);
        txtcolorG.setBounds(180, 57, 85, 22);

        txtCaloriasG.setBackground(new java.awt.Color(255, 255, 102));
        getContentPane().add(txtCaloriasG);
        txtCaloriasG.setBounds(180, 97, 85, 22);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiendapoo/grasas.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearGMouseClicked
        String nombreGrasa = txtnombreG.getText();
        String colorGrasa = txtcolorG.getText();
        int caloriasGrasa = Integer.parseInt(txtCaloriasG.getText());
        if (caloriasGrasa <= 300){
            JOptionPane.showMessageDialog(this, "Error, este alimento no es una grasa, verifique");
            return;
        }
        int pesoGrasa = Integer.parseInt(txtpesoG.getText());
        boolean esSaturada = CBGrasa.isSelected();

        Grasas Grasa1 = new Grasas (nombreGrasa, colorGrasa, caloriasGrasa, pesoGrasa, esSaturada);
        JOptionPane.showMessageDialog(this, Grasa1);
        listaAlim.add(Grasa1);
        this.setVisible(false);

    }//GEN-LAST:event_btnCrearGMouseClicked

    private void btnCrearGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearGActionPerformed

    private void txtnombreGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFGrasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFGrasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFGrasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFGrasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFGrasas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBGrasa;
    private javax.swing.JButton btnCrearG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCaloriasG;
    private javax.swing.JTextField txtcolorG;
    private javax.swing.JTextField txtnombreG;
    private javax.swing.JTextField txtpesoG;
    // End of variables declaration//GEN-END:variables
}
