/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tiendapoo;

import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Menu extends javax.swing.JFrame {

     private List<Alimentos> listaAlim = new ArrayList<>();

    public List<Alimentos> getListaFrutas() {
        return listaAlim;
    }

    public void setListaFrutas(List<Alimentos> listaFrutas) {
        this.listaAlim = listaFrutas;
    }
 
    /**
     Creates new form Menu
     */
    public Menu() {
       
       listaAlim = new ArrayList<>(); 
       initComponents();
       this.setLocationRelativeTo(null);
       setSize(520, 380); // Tamaño fijo
       setDefaultCloseOperation(EXIT_ON_CLOSE);
       setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnfrutas = new javax.swing.JButton();
        btngrasas = new javax.swing.JButton();
        btnchos = new javax.swing.JButton();
        btnmostrarlista = new javax.swing.JButton();
        btbremove = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 51));
        getContentPane().setLayout(null);

        btnfrutas.setBackground(new java.awt.Color(51, 255, 51));
        btnfrutas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnfrutas.setText("FRUTAS O VERDURAS");
        btnfrutas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnfrutasMouseClicked(evt);
            }
        });
        btnfrutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfrutasActionPerformed(evt);
            }
        });
        getContentPane().add(btnfrutas);
        btnfrutas.setBounds(140, 50, 200, 23);

        btngrasas.setBackground(new java.awt.Color(255, 204, 51));
        btngrasas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btngrasas.setText("GRASAS");
        btngrasas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btngrasasMouseClicked(evt);
            }
        });
        getContentPane().add(btngrasas);
        btngrasas.setBounds(190, 110, 110, 23);

        btnchos.setBackground(new java.awt.Color(51, 51, 255));
        btnchos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnchos.setText("CARBOHIDRATOS");
        btnchos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnchosMouseClicked(evt);
            }
        });
        getContentPane().add(btnchos);
        btnchos.setBounds(160, 180, 170, 23);

        btnmostrarlista.setBackground(new java.awt.Color(0, 204, 204));
        btnmostrarlista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnmostrarlista.setText("MOSTRAR LISTA");
        btnmostrarlista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmostrarlistaMouseClicked(evt);
            }
        });
        getContentPane().add(btnmostrarlista);
        btnmostrarlista.setBounds(30, 290, 170, 23);

        btbremove.setBackground(new java.awt.Color(255, 0, 0));
        btbremove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btbremove.setText("ELIMINAR");
        btbremove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btbremoveMouseClicked(evt);
            }
        });
        btbremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbremoveActionPerformed(evt);
            }
        });
        getContentPane().add(btbremove);
        btbremove.setBounds(300, 290, 170, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiendapoo/dfdf.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnfrutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfrutasActionPerformed
           
        JFFrutasVerduras ventana = new JFFrutasVerduras();
        ventana.setListaAlim(listaAlim);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnfrutasActionPerformed

    private void btnfrutasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfrutasMouseClicked
        
        
        
    }//GEN-LAST:event_btnfrutasMouseClicked

    private void btnmostrarlistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmostrarlistaMouseClicked
        StringBuilder sb = new StringBuilder();
    for (Object item : listaAlim) { 
        sb.append(item.toString()).append("\n");
    }
    JOptionPane.showMessageDialog(this, sb.toString());
    }//GEN-LAST:event_btnmostrarlistaMouseClicked

    private void btngrasasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngrasasMouseClicked
       JFGrasas ventana = new JFGrasas();
        ventana.setListaAlim(listaAlim);
        ventana.setVisible(true);
    }//GEN-LAST:event_btngrasasMouseClicked

    private void btnchosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnchosMouseClicked
       //se crea un objeto con la clase JFCarbos
        JFCarbos ventana = new JFCarbos();
       //Lo que entiendo es que al objeto se le agrega la informacion de la lista 
       ventana.setListaAlim(listaAlim);
       //el objeto podra ser visible
       ventana.setVisible(true);
    }//GEN-LAST:event_btnchosMouseClicked

    private void btbremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbremoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbremoveActionPerformed

    private void btbremoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbremoveMouseClicked
        listaAlim.remove(listaAlim.size()-1);
        JOptionPane.showMessageDialog(this, "El Ultimo alimento creado ha sido eliminado exitosamente");
    }//GEN-LAST:event_btbremoveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbremove;
    private javax.swing.JButton btnchos;
    private javax.swing.JButton btnfrutas;
    private javax.swing.JButton btngrasas;
    private javax.swing.JButton btnmostrarlista;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
